version: '3.4'

services:
  frontend:
    image: node:14.5-alpine3.12
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend:rw
    ports:
      - "8000:8000"
    command: tail -f /dev/null

  selenium:
    image: vvoyer/selenium-standalone
    ports:
      - "4444:4444"
